In [76]:
import numpy as np
import utils
from itertools import product
import sys

In [77]:
A = np.loadtxt('../data/evol_06.txt', dtype=int)
SL = []
ant_i = 0
for i in range(6,len(A)+1,6):
    SL.append(A[ant_i:i,:])
    ant_i = i
#utils.mostrar_evol([l.T for l in L])

In [78]:
B = np.loadtxt('../data/evol_06.txt', dtype=int)
CL = []
ant_i = 0
for i in range(6,len(A)+1,6):
    CL.append(np.clip(B[ant_i:i,:],0,1))
    ant_i = i

In [79]:
def check(SL,CL,U,b1,b2):
    for i in range(len(SL)-1):
        change_map = utils.change_map(SL[i],U,b1,b2)
        if not (change_map == CL[i+1]).all():
            return False
    return True

In [82]:
options = product(range(-2,3),repeat=11)

In [83]:
YL = []

In [ ]:
for i,D in enumerate(options):
    if i % 10000 == 0:
        # sys.stdout.write(str(len(YL))+' so far ('+str(i)+'/50M)\r')
        print(U)
    U = np.array(D[:9]).reshape((3,3))
    b1 = D[9]
    b2 = D[10]
    if check(SL,CL,U,b1,b2):
        YL.append((i,U,b1,b2))

[[-2 -2 -1]
 [-2 -1  2]
 [ 0 -1  1]]
[[-2 -2 -1]
 [-2  0  0]
 [ 1 -1  1]]
[[-2 -2 -1]
 [-2  1 -2]
 [ 2 -1  1]]
[[-2 -2 -1]
 [-2  1  2]
 [-2 -1  1]]
[[-2 -2 -1]
 [-2  2  0]
 [-1 -1  1]]
[[-2 -2 -1]
 [-1 -2 -2]
 [ 0 -1  1]]
[[-2 -2 -1]
 [-1 -2  1]
 [ 1 -1  1]]
[[-2 -2 -1]
 [-1 -1 -1]
 [ 2 -1  1]]
[[-2 -2 -1]
 [-1  0 -2]
 [-2 -1  1]]


In [67]:
YL

[(563881, array([[ 0,  2,  0],
         [ 0, -1,  0],
         [-1,  1,  0]]))]

In [58]:
U = np.array([[0,2,0],[0,-1,0],[-1,1,0]])
print(U)

[[ 0  2  0]
 [ 0 -1  0]
 [-1  1  0]]


In [59]:
PL = [SL[0]]
for S in SL:
    PL.append(utils.change_map(S,U))

In [62]:
PL = PL[:-1]

In [64]:
check(SL,PL,U)

True